import { LucideIcon } from 'lucide-react';

export enum UserRole {
  DIRECTOR = 'Diretor Comercial',
  MANAGER = 'Gerente Comercial',
  ENGINEER = 'Engenheiro de Aplicação',
  SELLER = 'Vendedor B2B'
}

export interface User {
  id: string;
  name: string;
  role: UserRole;
  email?: string;
}

export interface UserProfile {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  org_id: string;
}

export interface Invitation {
  id: string;
  email: string;
  role: UserRole;
  org_id: string;
  created_at: string;
}

export interface PlanOfAction {
  what: string;
  why: string;
  who: string;
  where: string;
  when: string;
  how: string;
  howMuch: string;
}

export interface ForecastHistory {
  id: string;
  date: string;
  report: string;
  nextStep: string;
  planOfAction?: PlanOfAction;
}

export type ConfidenceLevel = '0% (Perdida)' | '10% (Sonho)' | '30% (Orçamento)' | '40% (Demo)' | '50% (Interesse)' | '80% (Pedido/RFQ)' | '90% (Pedido/PO)' | '100% (Entregue)';

export interface ForecastItem {
  id: string;
  org_id: string;
  resp: string; // Email ou Nome
  respSigla: string; // EF, RG, WA, etc.
  customer: string;
  supplier: string;
  description: string;
  amount: number;
  uf: string;
  confidence: ConfidenceLevel;
  mar26: boolean;
  abr26: boolean;
  mai26: boolean;
  segSem26: boolean;
  followUp: string;
  contacts: string;
  tem_ea: boolean;
  pendencia_vendedor: boolean;
  nextStep: string;
  planOfAction?: PlanOfAction;
  history: ForecastHistory[];
  // Campos Pós-Venda
  po_numero?: string;
  nf_numero?: string;
  tipo_contrato?: 'Fornecimento' | 'Serviço' | 'Locação';
  data_faturamento?: string;
  status_entrega?: 'Aguardando' | 'Em trânsito' | 'Entregue';
  data_garantia?: string;
  nps?: number;
  melhorias?: string;
  arquivado?: boolean;
  quotes?: string[]; // URLs or names of uploaded Excel files
}

export interface SupplierBudget {
  id: string;
  name: string;
  goal: number;
  forecast: number;
}

export interface ClientBudget {
  id: string;
  org_id: string;
  name: string;
  sellerId: string;
  sellerName: string;
  year: number;
  month: number;
  suppliers: SupplierBudget[];
}

export enum Confidence {
  C0 = 0,
  C10 = 10,
  C30 = 30,
  C40 = 40,
  C50 = 50,
  C80 = 80,
  C90 = 90,
  C100 = 100
}

export interface Forecast {
  id: string;
  clientName: string;
  supplierName: string;
  sellerId: string;
  sellerName: string;
  amount: number;
  confidence: Confidence;
  segment: string;
  tem_ea: boolean;
  date: string;
  nextStep: string;
  history: ForecastHistory[];
}

export interface DashboardStats {
  totalGoal: number;
  totalForecast: number;
  progress: number;
}

export enum QuoteStatus {
  SENT = 'Enviado',
  APPROVED = 'Aprovado',
  LOST = 'Perdido'
}

export interface Quote {
  id: string;
  org_id: string;
  ref: string;
  date: string;
  brand: string;
  customerName: string;
  customerCnpj: string;
  totalAmountWithIcms: number;
  deliveryType: string;
  paymentTerms: string;
  deliveryTime: string;
  proposalValidity: string;
  status: QuoteStatus;
  lossReason?: string;
}

export interface Contact {
  id: string;
  name: string;
  role: string;
  phone: string;
  cell: string;
  email: string;
}

export interface Customer {
  id: string;
  org_id: string;
  cnpj: string;
  ie: string;
  name: string;
  nickname: string;
  address: string;
  cep: string;
  city: string;
  state: string;
  segment: 'Metalurgia' | 'Automotivo' | 'Energia' | 'Mineração' | 'Logística';
  seller: 'EF' | 'RG' | 'WA';
  contacts: Contact[];
  regions?: string;
}

export enum TaskCategory {
  SERVICE = 'Serviço',
  SATISFACTION = 'Satisfação',
  SALES = 'Vendas',
  MAINTENANCE = 'Manutenção'
}

export interface CommandCenterTask {
  id: string;
  org_id: string;
  title: string;
  description?: string;
  date: string;
  time: string;
  category: TaskCategory;
  completed: boolean;
  relatedForecastId?: string;
  isAutoGenerated?: boolean;
}
